# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\love0\OneDrive\桌面\report\QTUI\image_00.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QComboBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 40, 651, 51))
        font = QtGui.QFont()
        font.setFamily("隨峰體")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setLineWidth(1)
        self.label.setObjectName("label")
        self.Label_capture = QtWidgets.QLabel(self.centralwidget)
        self.Label_capture.setGeometry(QtCore.QRect(20, 140, 421, 581))
        font = QtGui.QFont()
        font.setFamily("隨峰體")
        font.setPointSize(24)
        self.Label_capture.setFont(font)
        self.Label_capture.setScaledContents(True)
        self.Label_capture.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_capture.setObjectName("Label_capture")
        self.PushBotton_correct = QtWidgets.QPushButton(self.centralwidget)
        self.PushBotton_correct.setGeometry(QtCore.QRect(680, 340, 93, 71))
        self.PushBotton_correct.setObjectName("PushBotton_correct")
        self.Label_after = QtWidgets.QLabel(self.centralwidget)
        self.Label_after.setGeometry(QtCore.QRect(780, 100, 481, 581))
        font = QtGui.QFont()
        font.setFamily("隨峰體")
        font.setPointSize(24)
        self.Label_after.setFont(font)
        self.Label_after.setScaledContents(True)
        self.Label_after.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_after.setObjectName("Label_after")
        self.comboBox_hairstyle = QComboBox(self.centralwidget)
        self.comboBox_hairstyle.setGeometry(QtCore.QRect(680, 500, 93, 31))
        self.comboBox_hairstyle.setObjectName("comboBox_hairstyle")
        self.comboBox_hairstyle.addItem("選擇髮型")

        
        self.PushBotton_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.PushBotton_cancel.setGeometry(QtCore.QRect(680, 240, 93, 71))
        self.PushBotton_cancel.setObjectName("PushBotton_cancel")
        self.PushBotton_get = QtWidgets.QPushButton(self.centralwidget)
        self.PushBotton_get.setGeometry(QtCore.QRect(680, 140, 93, 71))
        self.PushBotton_get.setObjectName("PushBotton_get")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1305, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "GUI圖形介面測試第二版"))
        self.Label_capture.setText(_translate("MainWindow", "攝像頭"))
        self.PushBotton_correct.setText(_translate("MainWindow", "確定"))
        self.Label_after.setText(_translate("MainWindow", "預覽圖"))
        self.PushBotton_cancel.setText(_translate("MainWindow", "取消"))
        self.PushBotton_get.setText(_translate("MainWindow", "拍照"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    
    # 在if __name__ == "__main__": 块中调用 setup_hairstyle_options 方法
    sys.exit(app.exec_())
    ui.setup_hairstyle_options()
    